(() => {
  "use strict";
  const G=window.PHASEV2,s=G.state,p=G.player,ctx=G.ctx;

  G.drawCollectibles=()=>{s.collectibles.forEach(item=>{if(item.collected)return;if(item.frequency!==null&&G.PRIMES[p.freqIndex]!==item.frequency)return;const pulse=0.5+0.5*Math.sin(G.gameTime*2+item.phase);ctx.save();ctx.globalCompositeOperation="lighter";ctx.fillStyle="rgba(215,235,255,"+(0.18+pulse*0.22)+")";ctx.shadowBlur=12;ctx.shadowColor="rgba(170,220,255,0.55)";ctx.beginPath();ctx.arc(item.x,item.y,3+pulse*1.5,0,G.TAU);ctx.fill();ctx.restore();});};

  G.drawTrail=()=>{if(p.trail.length<2)return;ctx.save();ctx.globalCompositeOperation="lighter";for(let i=1;i<p.trail.length;i++){const a=i/p.trail.length;ctx.strokeStyle="rgba(95,220,255,"+a*0.13+")";ctx.lineWidth=0.7+a*1.8;ctx.beginPath();ctx.moveTo(p.trail[i-1].x,p.trail[i-1].y);ctx.lineTo(p.trail[i].x,p.trail[i].y);ctx.stroke();}ctx.restore();};

  G.drawWaves=()=>{ctx.save();ctx.globalCompositeOperation="lighter";s.waves.forEach(w=>{const hue=G.primeHue(w.prime);ctx.strokeStyle="hsla("+hue+",95%,72%,"+w.alpha*0.42+")";ctx.lineWidth=5;ctx.shadowBlur=15;ctx.shadowColor="hsla("+hue+",95%,70%,0.6)";ctx.beginPath();ctx.arc(w.x,w.y,w.r,0,G.TAU);ctx.stroke();});ctx.restore();};

  G.drawBursts=()=>{s.bursts.forEach(b=>{const t=b.age/b.duration,hue=b.kind==="reject"?210:G.primeHue(b.prime);ctx.strokeStyle="hsla("+hue+",90%,76%,"+(1-t)*(b.kind==="friend"?0.2:0.48)+")";ctx.lineWidth=b.kind==="reject"?1.5:2;ctx.beginPath();ctx.arc(b.x,b.y,22+t*(b.kind==="friend"?95:58),0,G.TAU);ctx.stroke();});};

  G.drawSignal=()=>{const sig=s.signal;if(!sig.visible)return;const alpha=s.signalMet?0.76:0.42,hue=286,r=sig.broken?27:31;ctx.save();ctx.translate(sig.x,sig.y);ctx.rotate(sig.phase*0.35);ctx.globalCompositeOperation="lighter";ctx.shadowBlur=s.signalMet?20:12;ctx.shadowColor="hsla("+hue+",92%,68%,0.65)";ctx.strokeStyle="hsla("+hue+",92%,75%,"+alpha+")";ctx.lineWidth=1.7;ctx.beginPath();for(let i=0;i<5;i++){if(sig.broken&&i===4)continue;const a=-Math.PI/2+i*G.TAU/5,px=Math.cos(a)*r,py=Math.sin(a)*r;ctx.moveTo(0,0);ctx.lineTo(px,py);ctx.arc(px,py,2.4,0,G.TAU);}ctx.stroke();if(!sig.broken){ctx.strokeStyle="hsla("+hue+",100%,84%,0.42)";ctx.beginPath();for(let i=0;i<=5;i++){const a=-Math.PI/2+i*G.TAU/5,px=Math.cos(a)*r,py=Math.sin(a)*r;if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.closePath();ctx.stroke();ctx.fillStyle="rgba(240,230,255,0.88)";ctx.font="700 11px ui-monospace, monospace";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("φ",0,0);}ctx.restore();};

  G.drawPlayer=()=>{const prime=G.PRIMES[p.freqIndex],hue=G.primeHue(prime);ctx.save();ctx.translate(p.x,p.y);ctx.globalCompositeOperation="lighter";ctx.shadowBlur=22;ctx.shadowColor="hsla("+hue+",100%,70%,0.9)";ctx.fillStyle="hsla("+hue+",100%,82%,0.96)";ctx.beginPath();ctx.arc(0,0,p.radius,0,G.TAU);ctx.fill();ctx.strokeStyle="hsla("+hue+",100%,75%,0.24)";ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,18+Math.sin(G.gameTime*prime)*2,0,G.TAU);ctx.stroke();ctx.rotate(G.gameTime*0.22);ctx.beginPath();for(let i=0;i<=prime;i++){const a=i/prime*G.TAU,r=25,px=Math.cos(a)*r,py=Math.sin(a)*r;if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.stroke();ctx.restore();};
})();